name: Release
on:
  push:
    branches:
      - 'master'
jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      REGISTRY: docker.pkg.github.com
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE: argocd
    steps:
    - name: Source checkout
      uses: actions/checkout@v1
    - name: Docker build
      run: docker build . --tag localbuild/image:latest
    - uses: anchore/scan-action@master
      with:
        image-reference: "localbuild/image:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: false
    - name: anchore inline scan JSON results
      run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    - name: Create Version
      uses: caos/semantic-release@v0.2.4
    - name: Check if Version Tag is available
      if: env.CAOS_NEXT_VERSION ==  ''
      run: exit 1
    - name: Docker Login
      run: docker login $REGISTRY -u ${GITHUB_ACTOR} -p ${GITHUB_TOKEN}
    - name: Docker Tag Release
      run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:$CAOS_NEXT_VERSION
    - name: Docker Push Release
      run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:$CAOS_NEXT_VERSION
    - name: Docker Tag Latest
      run: docker tag localbuild/image:latest $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest
    - name: Docker Push Latest
      run: docker push $REGISTRY/$GITHUB_REPOSITORY/$IMAGE:latest
